db:
  postgresql:
    url: 'localhost'
    port: 5432
    database: 'yaml-db'

  sqlite:
    database: 'sqlite.db'

services:
  order-service:
    host: localhost
    port: 50001

  product-service:
    host: localhost
    port: 50003
